solve hw8 tasks
altengofso/java-course-2023 pull request #12
Opened 2023-12-03 19:06 UTC by altengofso

2023-12-14 20:43 UTC, SHvatov requested changes
@altengofso оставил комментарии, посмотри их, пожалуйста.

2023-12-14 20:43 UTC, SHvatov commented on src/main/java/edu/hw8/task1/Server.java
> +    private final ServerSocket serverSocket;
Сначала статики, потом поля, чтобы они не смешивались. Тяжело такое читать.

2023-12-14 20:43 UTC, SHvatov commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +        isAlive = new AtomicBoolean(true);
почему бы не в конструкторе это сделать?

2023-12-14 20:43 UTC, SHvatov commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            thread.interrupt();
на закрытие я бы джойнил все потоки к тому, в котором это самое закрытие происходит, чтобы гарантировать, что из метода мы выйдем только тогда, когда все потоки закончатся.

2023-12-18 11:22 UTC, altengofso commented on src/main/java/edu/hw8/task1/Server.java
> +    private final ServerSocket serverSocket;
исправил

2023-12-18 11:34 UTC, altengofso commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            thread.interrupt();
заменил прерывание на join

2023-12-18 11:35 UTC, altengofso commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +        isAlive = new AtomicBoolean(true);
перенес в конструктор

2023-12-19 16:04 UTC, SHvatov approved these changes
@altengofso 👍, можно мержить

2023-12-19 18:40 UTC, merged