solve hw9 tasks
altengofso/java-course-2023 pull request #13
Opened 2023-12-06 20:23 UTC by altengofso

2023-12-15 09:22 UTC, SHvatov requested changes
@altengofso оставил комментарии по первой задаче, задачи 2 и 3 👍

2023-12-15 09:22 UTC, SHvatov commented on src/main/java/edu/hw9/task1/MetricStats.java
> +    private volatile double sum;
оу ноу.... `volatile` конечно хорошо, но в реальной жизни советую его использовать только в крайних случаях - уж очень часто это приводит к ошибкам из-за некорректного использования

2023-12-15 09:22 UTC, SHvatov commented on src/main/java/edu/hw9/task1/MetricStats.java
> +    private volatile double sum;
если что, на помощь всегда придут `AtomicXXX`

2023-12-15 09:22 UTC, SHvatov commented on src/main/java/edu/hw9/task1/MetricUpdate.java
> +public record MetricUpdate(String name, double[] values) {
ИМХО, `MetricUpdateXXX` - не хватает суффикса, к примеру `Command`.  ДТО сам по себе не предполагает обновления - он хранит данные и все.

2023-12-15 09:22 UTC, SHvatov commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        executorGracefulShutdown();
`executorGracefulShutdown` - хорошо бы глагол в названии метода -> `performExecutorGracefulShutdown` или `shutdownExecutorGracefully`

2023-12-15 09:22 UTC, SHvatov commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        while (!executorService.isShutdown()) {
Не получится так, что ровно один поток в executo'е получит лок на монитор данного коллектора и будет потихоньку разбирать задачи? Можешь, пожалуйста, опровергнуть или подтвердить мое предположение?

2023-12-15 09:22 UTC, SHvatov commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        executorGracefulShutdown();
И этот метод - блокирующий. На будущее советую в таких случаях отдавать future, чтобы уже конечный пользователь решил, когда стоит получить асинхронно приготовленные данные.

2023-12-18 12:48 UTC, altengofso commented on src/main/java/edu/hw9/task1/MetricStats.java
> +    private volatile double sum;
добавил реализацию AtomicDouble, как это рекомендуется в документации https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/atomic/package-summary.html
изменил тип на AtomicDouble.
скорректировал код, который работает с этими полями.

2023-12-18 12:50 UTC, altengofso commented on src/main/java/edu/hw9/task1/MetricUpdate.java
> +public record MetricUpdate(String name, double[] values) {
MetricUpdate у меня используется только для временного хранения и передачи в класс MetricStats, где происходит чтение данных из этого ДТО и их обработка

2023-12-18 12:53 UTC, altengofso commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        while (!executorService.isShutdown()) {
да, получится именно так.
метод отмечен как synchronized
поэтому только один потом может в него зайти.
внутри метода потом будет блокироваться на queue.take(), пока очередь пуста.
и тем самым пока не получит сообщение об обновлении из очереди, ни один другой потом больше не сможет зайти в этот метод.
убрал synchronized

2023-12-18 13:27 UTC, altengofso commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        executorGracefulShutdown();
внес такие изменения:
stats - отдает Future<List<MetricStats>>, пользователь решает, когда получить данные. Больше не завершает работу сервиса
stop() - корректно завершает работу executor сервисов.
updateExecutorService с настраиваемым количеством потоков обрабатывает запросы на обновление статистик
statsExecutorService - пул виртуальных потоков, который обрабатывает запросы на получение статистик от коллектора

2023-12-19 15:56 UTC, SHvatov approved these changes
@altengofso теперь 👍, можно мержить)

2023-12-19 18:42 UTC, merged